export const SYSTEM_LOG_EVENTS = {
  CASBIN_RELOAD_FAILED: 'casbin.reload_failed',
  CASBIN_ENFORCE_FAILED: 'casbin.enforce_failed',
  CASBIN_WATCHER_PUBLISH_FAILED: 'casbin.watcher_publish_failed',
  CASBIN_WATCHER_EVENT_FAILED: 'casbin.watcher_event_failed',
  CASBIN_WATCHER_RESYNC_FAILED: 'casbin.watcher_resync_failed',
  AUDIT_WRITE_FAILED: 'audit.write_failed',
  INSTALLER_SETUP_FAILED: 'installer.setup_failed',
  INSTALLER_POLICY_RELOAD_FAILED: 'installer.policy_reload_failed',
  SYSTEM_LOG_WRITE_FAILED: 'system_log.write_failed',
  NOTIFICATION_SEND_FAILED: 'notification.send_failed',
  NOTIFICATION_TEMPLATE_NOT_FOUND: 'notification.template_not_found',
  NOTIFICATION_NO_RECIPIENTS: 'notification.no_recipients',
  NOTIFICATION_DELIVERY_FAILED: 'notification.delivery_failed',
  NOTIFICATION_CONNECTOR_FAILED: 'notification.connector_failed',
  NOTIFICATION_TEMPLATE_RENDER_FAILED: 'notification.template_render_failed',
  DATA_RETENTION_RUN_COMPLETED: 'data_retention.run_completed',
  DATA_RETENTION_STEP_FAILED: 'data_retention.step_failed',
  DATA_RETENTION_RUN_FAILED: 'data_retention.run_failed'
} as const;
